"""empty message

Revision ID: 576e766b9a23
Revises: 79db06d352ba
Create Date: 2022-11-29 23:02:34.986404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576e766b9a23'
down_revision = '79db06d352ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.alter_column('phoneNumber',
               existing_type=sa.INTEGER(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('businesses', schema=None) as batch_op:
        batch_op.alter_column('phoneNumber',
               existing_type=sa.String(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
